export default{
    "login": "rahuloo5",
    "id": 45355156,
    "node_id": "MDQ6VXNlcjQ1MzU1MTU2",
    "avatar_url": "https://avatars.githubusercontent.com/u/45355156?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/rahuloo5",
    "html_url": "https://github.com/rahuloo5",
    "followers_url": "https://api.github.com/users/rahuloo5/followers",
    "following_url": "https://api.github.com/users/rahuloo5/following{/other_user}",
    "gists_url": "https://api.github.com/users/rahuloo5/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/rahuloo5/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/rahuloo5/subscriptions",
    "organizations_url": "https://api.github.com/users/rahuloo5/orgs",
    "repos_url": "https://api.github.com/users/rahuloo5/repos",
    "events_url": "https://api.github.com/users/rahuloo5/events{/privacy}",
    "received_events_url": "https://api.github.com/users/rahuloo5/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Rahul Singh Tomar",
    "company": null,
    "blog": "https://portfolio-rahul.web.app/",
    "location": null,
    "email": null,
    "hireable": null,
    "bio": "Software developer (MERN)",
    "twitter_username": null,
    "public_repos": 31,
    "public_gists": 0,
    "followers": 0,
    "following": 4,
    "created_at": "2018-11-26T10:08:26Z",
    "updated_at": "2021-01-08T07:13:55Z"
  }